title: Nina Wade
description: 
theme: 

# Navigationseinträge
nav:
  - name: Start
    link: /Nina_Wade/
  - name: Über mich
    link: /Nina_Wade/about
  - name: Projekte
    link: /Nina_Wade/projects

