title: Meine Website
description: Eine einfache GitHub Pages Seite mit Jekyll
theme: jekyll-theme-minimal

# Navigationseinträge
nav:
  - name: Start
    link: /Nina_Wade/
  - name: Über mich
    link: /Nina_Wade/about
  - name: Projekte
    link: /Nina_Wade/projects

