title: Nina Wade
description: 
remote_theme: null

# Navigationseinträge
nav:
  - name: Start
    link: /Nina_Wade/
  - name: Über mich
    link: /Nina_Wade/about
  - name: Projekte
    link: /Nina_Wade/projects

